tiago_sea_configuration:
  arm_type:
    description: 'Arm type'
    choices: ['tiago-sea', 'no-arm']
    default_value: 'tiago-sea'
  end_effector:
    description: 'End effector model'
    choices: ['custom', 'no-end-effector', 'pal-pro-gripper']
    default_value: 'pal-pro-gripper'
  ft_sensor:
    description: 'FT sensor model'
    choices: ['rokubi', 'no-ft-sensor']
    default_value: 'rokubi'
  laser_model:
    description: 'Base laser model'
    choices: ['no-laser', 'sick-571', 'sick-561', 'sick-551', 'hokuyo']
    default_value: 'sick-571'
  camera_model:
    description: 'Head camera model'
    choices: ['orbbec-astra', 'orbbec-astra-pro', 'asus-xtion', 'no-camera']
    default_value: 'orbbec-astra'
  base_type:
    description: 'Base type'
    choices: ['pmb2', 'omni_base']
    default_value: 'omni_base'
  wrist_model:
    description: "Wrist model"
    choices: ['spherical-wrist']
    default_value: 'spherical-wrist'
  wheel_model:
    description: 'Wheel model'
    choices: ['nadia', 'moog']
    default_value: 'moog'
  has_velodyne:
    description: 'Has velodyne sensor'
    choices: ['False', 'True']
    default_value: 'False'
